[package]
name = "softlore"
version = "0.1.0"
authors = ["Reuben Tier <reuben.tier@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
